name: Release

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: 'Valid semver number syntax <x.x.x> (ex: 0.0.1)'
        required: true
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pages: write
  id-token: write

run-name: Release v${{ github.event.inputs.strategy || github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'tduyng' || github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.25'

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Create release (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION="${{ github.event.inputs.strategy }}"
          just tag $VERSION
          git push origin HEAD:main
          git push origin v$VERSION

      - name: Generate changelog (tag push)
        if: github.event_name == 'push'
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "Generating changelog for existing tag $GITHUB_REF_NAME..."
          git cliff --latest --strip all --output LATEST_CHANGELOG.md

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean --release-notes LATEST_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-docs:
    name: Deploy Docs
    needs: release
    uses: ./.github/workflows/docs.yml
    permissions:
      contents: read
      pages: write
      id-token: write
