name: Release

on:
  workflow_dispatch:
    inputs:
      strategy:
        description: 'Valid semver number syntax <x.x.x> (ex: 0.0.1)'
        required: true

permissions:
  contents: write

run-name: Release v${{ inputs.strategy }}

jobs:
  release:
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'tduyng' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - name: Run make tag
        env:
          VER: ${{ github.event.inputs.strategy }}
        run: make tag

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean --release-notes LATEST_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
